### ISSUE TITLE
Reply-Comments cut off the original post

### ISSUE THREAD

**Issue by TilmanDW** [DW-ReCo/kid-game-framework#118] opened 2021-11-15 14:38 UTC
Reply-Commented posts are cut off (see example of Financial Times Post commented and resent by Janello Mao

![Screenshot 2021-11-15 at 15 37 07](https://user-images.githubusercontent.com/88382494/141800243-1a986125-29aa-4d38-86ac-27e8d21c9357.png)
)

**Comment by nikonikoniko** [comment] 2021-11-15 14:42
duplicate of https://github.com/DW-ReCo/kid-game-framework/issues/96

**Closed by nikonikoniko** 2021-11-15 14:42 UTC
